<?xml version="1.0" encoding="utf-8"?><Database Name="FilmDB" Class="VideoDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=FilmDB;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="VideoLibDAL.Properties.Settings" SettingsPropertyName="FilmDBConnectionString" Provider="System.Data.SqlClient" />
</Database>